### ISSUE TITLE
arm_neon.h 在哪里

### ISSUE THREAD

**Issue by muyuuuu** [kkchenlight/Arm-Optimizing-C-code-with-Neon-intrinsics#1]
灵魂发问，在 `ubuntu` 这种开发平台，`#include <arm_neon.h>` 一直报错，无法找到文件。

你这个是在啥平台，或者说有没有安装额外的依赖库？

~~搜遍了全网，都是再讲 `neon` 指令，就是找不到一个环境配置的~~

**Comment by kkchenlight** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        不好意思，才关注到你这个邮件。需要你是arm的cpu才可以，就是你的系统可以是ubuntu，但你的cpu得是arm的，然后在标准库里会带有<arm_neon.h> 这个文件。你是直接在github上看到的吗，还是看到博客了，博客上应该有我其他联系方式
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                kkchen.lg
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年07月25日 10:58
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [kkchenlight/Arm-Optimizing-C-code-with-Neon-intrinsics] arm_neon.h 在哪里 (Issue #1)
        
      
    
  
  
灵魂发问，在 ubuntu 这种开发平台，#include <arm_neon.h> 一直报错，无法找到文件。
你这个是在啥平台，或者说有没有安装额外的依赖库？
搜遍了全网，都是再讲 neon 指令，就是找不到一个环境配置的

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by muyuuuu** [comment]
原来都是一年前的问题了.......那会儿刚入门，不太熟练。

简而言之总结一下就是，ubuntu 写代码，用 NDK 编译代码，放到 Android 平拍运行，arm 系列的 CPU 会有 <arm_neon.h> 这个文件。
